name: Docker Compose Up & Generate Env

on:
  workflow_dispatch:  # 수동 실행용 트리거

jobs:
  deploy-docker-containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run docker-compose up -d
        run: |
          cd /var/lib/pgsql/data/service_templates/Docker/yaml
          docker-compose up -d

      - name: Generate docker_env.sh
        run: |
          chmod +x /var/lib/pgsql/data/service_templates/Docker/scripts/docker_compose.sh
          /var/lib/pgsql/data/service_templates/Docker/scripts/docker_compose.sh
          cat /var/lib/pgsql/data/service_templates/Docker/docker_env.sh/docker_env.sh

      - name: Copy to .env
        run: cp /var/lib/pgsql/data/service_templates/Docker/docker_env.sh/docker_env.sh .env


      - name: Upload .env as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-env
          path: .env
