name: Docker Compose Up & Env Generator

on:
  push:
    branches:
      - main

jobs:
  docker-up-and-generate-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build and run containers
        run: docker-compose up -d

      - name: Generate docker_env.sh
        run: |
          chmod +x generate_docker_env.sh
          ./generate_docker_env.sh
          cat docker_env.sh

      - name: Copy to .env file
        run: cp docker_env.sh .env

      - name: Upload .env as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-env
          path: .env
